name: Stop Minecraft Server

on:
  workflow_dispatch:

jobs:
  stop-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Stop Minecraft server
        run: |
          pkill -f "java -Xmx1024M -Xms1024M -jar /path/to/your/fabric-server.jar nogui"
